apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: webapp1
spec:
  selector:
    matchLabels:
      app: webapp1
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
