on: push
name: Deploy
jobs:
  deploy:
    name: Deploy to k8s cluster
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout repo
      uses: actions/checkout@main

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: walpab21/homelab:latest,walpab21/homelab:${{ github.sha }}

    - name: Deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: set image deployment/webapp1-deployment webapp1=${{ github.repository }}:${{ github.sha }}

    - name: Verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: rollout status deployment/webapp1-deployment
